### ISSUE TITLE
Is there a way to open multiple workbooks in the same program?

### ISSUE THREAD

**Issue by mikeThurmond** [mebaran/clj-excel#14]
I'm opening a wb with the following:

    (defn parse-workbook [file sheet]
        (drop 1 (-> (lazy-workbook (workbook-xssf file))
                            (get sheet))))

Is it possible to open multiple workbooks?  I can get the first wb parsed, but when I move onto the second one I get this error: IllegalArgumentException Cannot open <nil> as an InputStream.  clojure.java.io/fn--9498 (io.clj:167)

My thought was that I need to close the first wb OR use with open when I'm parsing.

**Comment by mebaran** [comment]
Hey Mike,

I haven’t maintained this project in awhile so it’s IO handling might be wonky for modern Clojure.  If you see an easy fix, feel free to send me a pill request and I’ll apply it!

Best,
Mark

Sent on the go
________________________________

**Comment by mikeThurmond** [comment]
Thanks
